# syntax=docker/dockerfile:1.7

############################
# Build stage
############################
FROM golang:1.24.3 AS builder

WORKDIR /src

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    go build \
    -trimpath \
    -ldflags="-s -w" \
    -o /tailscope \
    ./cmd

############################
# Runtime stage
############################
FROM alpine:3.22

RUN apk --no-cache add ca-certificates

RUN addgroup -S tailscope && \
    adduser -S tailscope -G tailscope

WORKDIR /app

COPY --from=builder /tailscope .

USER tailscope

EXPOSE 8080

ENTRYPOINT ["./tailscope"]